/**
 * Design token CSS custom property names for Rell UI.
 * Use with React style prop for autocomplete when overriding theme:
 * style={{ '--rell-bg-primary': '#fff' } as React.CSSProperties & Partial<RellDesignTokens> }
 */

export type RellDesignTokenKey =
  | '--rell-bg-primary'
  | '--rell-bg-secondary'
  | '--rell-bg-tertiary'
  | '--rell-bg-elevated'
  | '--rell-surface-base'
  | '--rell-surface-hover'
  | '--rell-surface-active'
  | '--rell-surface-disabled'
  | '--rell-border-default'
  | '--rell-border-hover'
  | '--rell-border-focus'
  | '--rell-border-error'
  | '--rell-border-success'
  | '--rell-text-primary'
  | '--rell-text-secondary'
  | '--rell-text-tertiary'
  | '--rell-text-disabled'
  | '--rell-text-inverse'
  | '--rell-accent-cyan'
  | '--rell-accent-magenta'
  | '--rell-accent-yellow'
  | '--rell-accent-green'
  | '--rell-accent-pink'
  | '--rell-accent-blue'
  | '--rell-status-success'
  | '--rell-status-warning'
  | '--rell-status-error'
  | '--rell-status-info'
  | '--rell-interactive-primary'
  | '--rell-interactive-primary-hover'
  | '--rell-interactive-primary-active'
  | '--rell-interactive-secondary'
  | '--rell-interactive-secondary-hover'
  | '--rell-interactive-secondary-active'
  | '--rell-font-sans'
  | '--rell-font-mono'
  | '--rell-spacing-1'
  | '--rell-spacing-2'
  | '--rell-spacing-3'
  | '--rell-spacing-4'
  | '--rell-spacing-5'
  | '--rell-spacing-6'
  | '--rell-spacing-8'
  | '--rell-spacing-10'
  | '--rell-spacing-12'
  | '--rell-shadow-sm'
  | '--rell-shadow-base'
  | '--rell-shadow-md'
  | '--rell-shadow-lg'
  | '--rell-shadow-xl'
  | '--rell-radius-sm'
  | '--rell-radius-base'
  | '--rell-radius-md'
  | '--rell-radius-lg'
  | '--rell-radius-xl'
  | '--rell-radius-2xl'
  | '--rell-radius-full';

/** Map of design token keys to CSS values (string). Use with style prop when theming. */
export type RellDesignTokens = Partial<Record<RellDesignTokenKey, string>>;
